### ISSUE TITLE
Option to use other markdown parser

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/app-extension-qmarkdown#38]
Currently the package uses `markdown-it` which is one of the "bigger" markdown parsers.

https://bundlephobia.com/result?p=@quasar/quasar-app-extension-qmarkdown@1.0.0-beta.21

When checking some others I found `snarkdown` to be a very small one. 33 times smaller gzipped

<img width="476" alt="Screenshot 2019-10-19 10 07 51" src="https://user-images.githubusercontent.com/3253920/67135779-69f1aa00-f258-11e9-82e4-b361e5c6b024.png">

edit:
URL marked: https://marked.js.org/#/README.md#README.md
URL snarkdown: https://github.com/developit/snarkdown

**Comment by hawkeye64** [comment]
You can create another app extension using snarkdown if you like. I looked, and while it seems nice and small, it doesn't do everything and there are some other issues as well (because it uses regex).
But thanks for bringing it up. I had never heard of it before.

**Comment by mesqueeb** [comment]
@hawkeye64 how about swapping `markdown-it` for `marked`? It's around 5 times smaller than markdown-it.

When you look at loading speeds:
https://bundlephobia.com/scan-results?packages=marked,markdown-it
While markdown-it would take 1 second to load on 2G, marked would take 200ms.

**Comment by hawkeye64** [comment]
@mesqueeb I would have at the beginning when this was evolving, but I am afraid it'd break everything and everyone using it.
Perhaps a new UI/app-ext Luca?
