### ISSUE TITLE
Add mentions rendering option

### ISSUE THREAD

**Issue by VIM-Arcange** [quasarframework/app-extension-qmarkdown#6]
It would be nice to have a "mentions" rendering option like showdown is doing with ghMentions and ghMentionsLink

description: https://github.com/showdownjs/showdown/wiki/Showdown-options
implementation: https://github.com/showdownjs/showdown/blob/4da93e8e136e5cc1f13ad2b3d5477c14e11aaafd/src/subParsers/makehtml/links.js#L251

**Comment by hawkeye64** [comment]
Will add the ability for dev users to add to the markdown-it processing.

**Comment by hawkeye64** [comment]
Please refer to #7
